---
- name: Install haproxy
  ansible.builtin.apt:
    pkg:
      - haproxy
    update_cache: true

- name: Start haproxy
  ansible.builtin.systemd_service:
    name: haproxy.service
    state: started
    daemon_reload: true
    enabled: true
