apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-rules
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    path: manifests/alert-rules
    repoURL: https://github.com/ophum/homelab.git
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
