apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    path: manifests/applications
    repoURL: https://github.com/ophum/homelab.git
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
