apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: cnpg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 4.11.2
    helm:
      releaseName: ingress-nginx
      values: |
        monitoring:
          grafanaDashboard:
            create: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
