apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 62.3.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          crds:
            enabled: false

          defaultDashboardTimezone: Asia/Tokyo
          adminPassword: <path:secret/data/kube-prometheus-stack#adminPassword>
          grafana:
            persistence:
              enabled: true
              type: sts
              accessModes:
                - ReadWriteOnce
              size: 10Gi
              finalizers:
                - kubernetes.io/pvc-protection
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
