apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    path: manifests/mattermost
    repoURL: https://github.com/ophum/homelab.git
  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost
