apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: operator
    repoURL: https://operator.min.io
    targetRevision: 6.0.3
    helm:
      releaseName: operator

  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
