apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: prometheus-operator-crds
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 14.0.0 # Replace with the Longhorn version you'd like to install or upgrade to
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
