apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: promtail
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.16.5
    helm:
      releaseName: promtail
      values: |
        config:
        # publish data to loki
          clients:
            - url: http://loki-gateway/loki/api/v1/push
              tenant_id: 1

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
