apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.28.1
    helm:
      values: |
        ui:
          enabled: true
          serviceType: NodePort

        server:
          ha:
            enabled: true
            raft:
              enabled: true
          
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: vault.homelab.t-inagaki.net

          dataStorage:
            enabled: true
            size: 3G
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
