apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  annotations:
    avp.kubernetes.io/path: homelab/data/argocd-cm
data:
  # Kustomize sees the value of dex.config as a single string instead of yaml. It will not merge
  # Dex settings, but instead it will replace the entire configuration with the settings below,
  # so add these to the existing config instead of setting them in a separate file
  url: https://argocd.homelab.t-inagaki.net:8443
  users.anonymous.enabled: "false"
  exec.enabled: "true"
  dex.config: |
    # Setting staticClients allows Argo Workflows to use Argo CD's Dex installation for authentication
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: <github_client_id>
          clientSecret: <github_client_secret>
          orgs:
            - name: <org_name>

            #staticClients:
            #  # This is the OIDC client ID in plaintext
            #  - id: argo-workflows-sso
            #    name: Argo Workflow
            #    redirectURIs:
            #      - https://argo-workflows.mydomain.com/oauth2/callback
            #    secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
