apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.2/manifests/install.yaml
  - cmp-plugin.yaml
  - argocd-vault-plugin-credentials.yaml
  - role-and-role-binding.yaml
  - argocd-server-ingress.yaml

patches:
  - path: argocd-repo-server.yaml
  - path: argocd-cm.yaml
  - path: argocd-rbac-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
