apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  labels:
    release: kube-prometheus-stack
spec:
  instances: 3

  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
