resources:
  - https://github.com/minio/operator/examples/kustomization/base/

patches:
  - target:
      kind: Tenant
      name: myminio
    patch: |
      - op: replace
        path: /spec/pools/0/servers
        value: 4
      - op: replace
        path: /spec/pools/0/volumesPerServer
        value: 1
      - op: replace
        path: /spec/pools/0/volumeClaimTemplate/spec/resources/requests/storage
        value: 5Gi
      - op: replace
        path: /spec/pools/0/volumeClaimTemplate/spec/storageClassName
        value: longhorn
