apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
spec:
  size: 100users
  ingress:
    enabled: true
    host: chat.homelab.t-inagaki.net
  database:
    external:
      secret: postgres-conenction
  fileStore:
    external:
      url: minio.minio-tenant.svc.cluster.local
      bucket: mattermost
      secret: minio-access-key
  mattermostEnv:
    - name: MM_SERVICESETTINGS_ENABLEINSECUREOUTGOINGCONNECTIONS
      value: "true"
  version: 9.11.1
