apiVersion: v1
kind: Secret
metadata:
  name: minio-access-key
  annotations:
    avp.kubernetes.io/path: homelab/data/mattermost
type: Opaque
stringData:
  accesskey: <minio_access_key>
  secretkey: <minio_secret_key>
